### PR TITLE
Allow signing assertion instead of the response

### PR DESCRIPTION
**Pull request by secretgu**
Tested signing assertion only and response only with a GSA built with cl/84821935.

### CODE REVIEW

**Comment by macpd** [comment]
I'm not very familiar with this code, but the changes LGTM.  Have you tested this?

**Comment by secretgu** [comment]
Yes. Tested signing assertion only and response only with a GSA built with cl/84821935.

**Comment by macpd** [comment]
great. thanks for confirming

**Comment by secretgu** [comment]
Sure.

**Pull request merged**
